FROM mcr.microsoft.com/dotnet/sdk:5.0

LABEL description="FreeSWITCH Esl2Http cross-platform adapter microservice"
LABEL author=aloz

################ Build arguments ################

# The source code need to be built inside the container
ARG DIR_BUILD=/tmp/Esl2Http-build
ARG DIR_PUBLISH=/opt

ARG MICROSVC_NAME=Esl2Http
ARG MICROSVC_USER=Esl2Http

################ Build arguments ################

# Applying the latest updates
# Installing dotnet prepequesites
RUN apt-get update && \
    apt-get --yes dist-upgrade

# The user to run the microservice
RUN adduser --disabled-password --system --gecos "FreeSWITCH Esl2Http cross-platform adapter microservice" --force-badname $MICROSVC_USER

WORKDIR $DIR_BUILD

# Copying microservice sources
WORKDIR $DIR_BUILD/src/$MICROSVC_NAME
COPY $MICROSVC_NAME.sln .
COPY $MICROSVC_NAME $MICROSVC_NAME
COPY $MICROSVC_NAME.Private $MICROSVC_NAME.Private

# Building microservice executable
# Cleanup build directory
RUN dotnet restore $MICROSVC_NAME.sln && \
    dotnet build $MICROSVC_NAME.sln -c Release -o $DIR_BUILD/build/$MICROSVC_NAME && \
    dotnet publish $MICROSVC_NAME.sln -c Release -o $DIR_PUBLISH/$MICROSVC_NAME && \
    rm -rf $DIR_BUILD

USER $MICROSVC_USER
ENV ESL2HTTP_ENTRYPOINT=$DIR_PUBLISH/$MICROSVC_NAME/$MICROSVC_NAME
ENTRYPOINT $ESL2HTTP_ENTRYPOINT
